site_name: SpikeGLX
nav:
    - Home: ./
    - Firmware: firmware/
    - Legacy: legacy/
    - Help:
        - 'Neuropixels Slack Channel': 'https://join.slack.com/t/neuropixelsgroup/shared_invite/zt-1jibcdbhe-uNyp8q522L4S0apVKwoC6A'
        - 'Neuropixels Support Page': 'https://www.neuropixels.org/support'
        - 'Noise: Reference and Ground': 'help/Ref_gnd/'
        - 'Noise: Learn How To Solder': 'help/solder/solder/'
        - 'Sharpening Apparatus (MS.Word.docx)': 'Support/NPix_sharpening.docx'
        - 'PXIe Quickstart': 'Sgl_help/SpikeGLX_PXIe_Quickstart.html'
        - 'OneBox Quickstart': 'Sgl_help/SpikeGLX_OneBox_Quickstart.html'
        - 'Quadbase Quickstart': 'Sgl_help/SpikeGLX_Quadbase_Quickstart.html'
        - 'SpikeGLX Tutorials': 'Sgl_help/Tutorials/tutorial_toc.html'
        - 'SpikeGLX UserManual': 'Sgl_help/UserManual.html'
        - 'SpikeGLX Dirs and Files': 'help/SpikeGLX_dirs_files/'
        - 'SpikeGLX Broken Shank Support': 'Sgl_help/SpikeGLX_Broken_Shank_Support.html'
        - 'SpikeGLX QuickRef': 'Support/SpikeGLX_QuickRef.html'
        - 'SpikeGLX UCL Course 2025': 'Support/UCL-Course-BillKarsh-2025.html'
        - 'SpikeGLX UCL Course 2024': 'Support/UCL-Course-BillKarsh-2024.html'
        - 'SpikeGLX FAQ': 'Sgl_help/SpikeGLX_FAQ.html'
        - 'Metadata Help': 'Sgl_help/Metadata_Help.html'
        - 'CatGT ReadMe': 'CatGT_help/CatGT_ReadMe.html'
        - 'CatGT: Tshift, CAR, Gfix': 'help/catgt_tshift/catgt_tshift/'
        - 'Sync: Aligning with Edges': 'help/syncEdges/Sync_edges/'
        - 'IMRO Table Anatomy': 'help/imroTables/'
    - New: new/
theme: mkdocs
